import '../../../domain/enums/roles.dart';
import '../../../domain/models/match_details/score_card.dart';

List<ScoreCardModel> scoreboard = [
  ScoreCardModel(
      name: "Richard Parker",
      runs: "23",
      balls: "16",
      fours: "2",
      sixes: "3",
      strikeRate: "0.21",
      status: "b Ben Victor c Oliver",
      role: Role.batting),
  ScoreCardModel(
      name: "Courtney Henry",
      runs: "23",
      balls: "16",
      fours: "2",
      sixes: "3",
      strikeRate: "0.21",
      status: "b Ben Victor c Oliver",
      role: Role.batting),
  ScoreCardModel(
      name: "Guy Hawkins",
      runs: "23",
      balls: "16",
      fours: "2",
      sixes: "3",
      strikeRate: "0.21",
      status: "b Ben Victor c Oliver",
      role: Role.batting),
  ScoreCardModel(
      name: "Arlene McCoy",
      runs: "23",
      balls: "16",
      fours: "2",
      sixes: "3",
      strikeRate: "0.21",
      status: "not out",
      role: Role.batting),
  ScoreCardModel(
      name: "Annette Black",
      runs: "23",
      balls: "16",
      fours: "2",
      sixes: "3",
      strikeRate: "0.21",
      status: "not out",
      role: Role.batting),
  ScoreCardModel(
    name: "Ronald Richards",
    dots: "0",
    maiden: " 0",
    runs: "31",
    wickets: "1",
    economy: "9.3",
    role: Role.bowling,
  ),
  ScoreCardModel(
    name: "Ronald Richards",
    dots: "0",
    maiden: " 0",
    runs: "31",
    wickets: "1",
    economy: "9.3",
    role: Role.bowling,
  ),
  ScoreCardModel(
    name: "Ronald Richards",
    dots: "0",
    maiden: " 0",
    runs: "31",
    wickets: "1",
    economy: "9.3",
    role: Role.bowling,
  ),
  ScoreCardModel(
    name: "Ronald Richards",
    dots: "0",
    maiden: " 0",
    runs: "31",
    wickets: "1",
    economy: "9.3",
    role: Role.bowling,
  ),
  ScoreCardModel(
    name: "Ronald Richards",
    dots: "0",
    maiden: " 0",
    runs: "31",
    wickets: "1",
    economy: "9.3",
    role: Role.bowling,
  )
];
